In [1]:
%load_ext autoreload
%autoreload 2

import SRP.SRP as Srp
import numpy as np

Failed experiment: using xor to change the sign is not faster than sending the arithmetic to BLAS as a dot product.

In [2]:
hasher = Srp(1280)

In [3]:
hasher.stable_transform("foo bar bar")

array([-21.52177334,   0.69314671,   0.69314671, ...,  21.52177334,
         0.69314671,   0.69314671])

In [4]:
hasher.xor_transform("foo bar bar")

array([4.62176563e+10, 2.23645676e+10, 2.23645676e+10, ...,
       0.00000000e+00, 2.23645676e+10, 2.23645676e+10])

In [5]:
import string
import random
import time
time.time()

def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
   return ''.join(random.choice(chars) for _ in range(size))

id_generator(3)

methods = [
    ("old", hasher.stable_transform),
    ("new", hasher.xor_transform)
]

fake_vocab = [id_generator(6) for i in range(1000000)]

In [6]:
fake_vocab = set(fake_vocab)
len(fake_vocab)

999775

Pre-Calculate the hashes to avoid privileging one method or the other.

In [7]:
for i, vocab in enumerate(fake_vocab):
    hasher.hash_string(vocab)

In [32]:
times = {"old":0, "new": 0}


In [35]:
for i in range(100): 
    book = random.sample(fake_vocab, 10000)
    counts = np.random.zipf(1.9,10000).astype(np.float32)
    random.shuffle(methods)
    for method in methods:
        lab = method[0]
        start = time.time()
        method[1](book, counts, log = True, standardize=False)
        times[lab] += time.time() - start
times

{'new': 30.02587652206421, 'old': 5.331396102905273}

In [ ]:
hasher.xor_transform(book, counts, log = True, standardize=False)


array([  32.50130213,   91.25606427, -179.92709585, ..., -112.01094953,
        -28.18608706, -179.08342092])

In [ ]:
time_

time.time()